apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  RAILS_ENV: "production"
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "true"
  PORT: "3000"
  WEB_CONCURRENCY: "2"
  RAILS_MAX_THREADS: "5"
  SECRET_KEY_BASE: "7c25f02377d9a50dd2752bd1ce7fb13caf6ff09ccebd5d1bbf6859f5f73d0bdc229b420052b9fdb2f1520bae3adf567fd2284bc7e6b1bc1092c5200931c51e84"
